version: '3.0'

services:

  collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    container_name: collector
    hostname: collector
    command: ["--config=/etc/collector-config.yaml"]
    environment:
      - AWS_ACCESS_KEY_ID=AKIAW4VMEYGDVQH3KM7O
      - AWS_SECRET_ACCESS_KEY=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
    volumes:
      - ./collector-config-aws.yaml:/etc/collector-config.yaml
      - ~/.aws:/root/.aws
    ports:
      - "5555:5555"
